/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppYourWorkRouteImport } from './routes/_app/your-work'
import { Route as AppProjectsRouteImport } from './routes/_app/projects'
import { Route as AppProjectsProjectKeyRouteImport } from './routes/_app/projects.$projectKey'
import { Route as AppProjectsProjectKeyIndexRouteImport } from './routes/_app/projects.$projectKey.index'
import { Route as AppProjectsProjectKeyRoadmapRouteImport } from './routes/_app/projects.$projectKey.roadmap'
import { Route as AppProjectsProjectKeyMembersRouteImport } from './routes/_app/projects.$projectKey.members'
import { Route as AppProjectsProjectKeyBoardRouteImport } from './routes/_app/projects.$projectKey.board'
import { Route as AppProjectsProjectKeyBacklogRouteImport } from './routes/_app/projects.$projectKey.backlog'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppYourWorkRoute = AppYourWorkRouteImport.update({
  id: '/your-work',
  path: '/your-work',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectKeyRoute = AppProjectsProjectKeyRouteImport.update({
  id: '/$projectKey',
  path: '/$projectKey',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppProjectsProjectKeyIndexRoute =
  AppProjectsProjectKeyIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsProjectKeyRoute,
  } as any)
const AppProjectsProjectKeyRoadmapRoute =
  AppProjectsProjectKeyRoadmapRouteImport.update({
    id: '/roadmap',
    path: '/roadmap',
    getParentRoute: () => AppProjectsProjectKeyRoute,
  } as any)
const AppProjectsProjectKeyMembersRoute =
  AppProjectsProjectKeyMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AppProjectsProjectKeyRoute,
  } as any)
const AppProjectsProjectKeyBoardRoute =
  AppProjectsProjectKeyBoardRouteImport.update({
    id: '/board',
    path: '/board',
    getParentRoute: () => AppProjectsProjectKeyRoute,
  } as any)
const AppProjectsProjectKeyBacklogRoute =
  AppProjectsProjectKeyBacklogRouteImport.update({
    id: '/backlog',
    path: '/backlog',
    getParentRoute: () => AppProjectsProjectKeyRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/your-work': typeof AppYourWorkRoute
  '/projects/$projectKey': typeof AppProjectsProjectKeyRouteWithChildren
  '/projects/$projectKey/backlog': typeof AppProjectsProjectKeyBacklogRoute
  '/projects/$projectKey/board': typeof AppProjectsProjectKeyBoardRoute
  '/projects/$projectKey/members': typeof AppProjectsProjectKeyMembersRoute
  '/projects/$projectKey/roadmap': typeof AppProjectsProjectKeyRoadmapRoute
  '/projects/$projectKey/': typeof AppProjectsProjectKeyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/your-work': typeof AppYourWorkRoute
  '/projects/$projectKey/backlog': typeof AppProjectsProjectKeyBacklogRoute
  '/projects/$projectKey/board': typeof AppProjectsProjectKeyBoardRoute
  '/projects/$projectKey/members': typeof AppProjectsProjectKeyMembersRoute
  '/projects/$projectKey/roadmap': typeof AppProjectsProjectKeyRoadmapRoute
  '/projects/$projectKey': typeof AppProjectsProjectKeyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/projects': typeof AppProjectsRouteWithChildren
  '/_app/your-work': typeof AppYourWorkRoute
  '/_app/projects/$projectKey': typeof AppProjectsProjectKeyRouteWithChildren
  '/_app/projects/$projectKey/backlog': typeof AppProjectsProjectKeyBacklogRoute
  '/_app/projects/$projectKey/board': typeof AppProjectsProjectKeyBoardRoute
  '/_app/projects/$projectKey/members': typeof AppProjectsProjectKeyMembersRoute
  '/_app/projects/$projectKey/roadmap': typeof AppProjectsProjectKeyRoadmapRoute
  '/_app/projects/$projectKey/': typeof AppProjectsProjectKeyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/projects'
    | '/your-work'
    | '/projects/$projectKey'
    | '/projects/$projectKey/backlog'
    | '/projects/$projectKey/board'
    | '/projects/$projectKey/members'
    | '/projects/$projectKey/roadmap'
    | '/projects/$projectKey/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/projects'
    | '/your-work'
    | '/projects/$projectKey/backlog'
    | '/projects/$projectKey/board'
    | '/projects/$projectKey/members'
    | '/projects/$projectKey/roadmap'
    | '/projects/$projectKey'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/signup'
    | '/_app/projects'
    | '/_app/your-work'
    | '/_app/projects/$projectKey'
    | '/_app/projects/$projectKey/backlog'
    | '/_app/projects/$projectKey/board'
    | '/_app/projects/$projectKey/members'
    | '/_app/projects/$projectKey/roadmap'
    | '/_app/projects/$projectKey/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/your-work': {
      id: '/_app/your-work'
      path: '/your-work'
      fullPath: '/your-work'
      preLoaderRoute: typeof AppYourWorkRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectKey': {
      id: '/_app/projects/$projectKey'
      path: '/$projectKey'
      fullPath: '/projects/$projectKey'
      preLoaderRoute: typeof AppProjectsProjectKeyRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/projects/$projectKey/': {
      id: '/_app/projects/$projectKey/'
      path: '/'
      fullPath: '/projects/$projectKey/'
      preLoaderRoute: typeof AppProjectsProjectKeyIndexRouteImport
      parentRoute: typeof AppProjectsProjectKeyRoute
    }
    '/_app/projects/$projectKey/roadmap': {
      id: '/_app/projects/$projectKey/roadmap'
      path: '/roadmap'
      fullPath: '/projects/$projectKey/roadmap'
      preLoaderRoute: typeof AppProjectsProjectKeyRoadmapRouteImport
      parentRoute: typeof AppProjectsProjectKeyRoute
    }
    '/_app/projects/$projectKey/members': {
      id: '/_app/projects/$projectKey/members'
      path: '/members'
      fullPath: '/projects/$projectKey/members'
      preLoaderRoute: typeof AppProjectsProjectKeyMembersRouteImport
      parentRoute: typeof AppProjectsProjectKeyRoute
    }
    '/_app/projects/$projectKey/board': {
      id: '/_app/projects/$projectKey/board'
      path: '/board'
      fullPath: '/projects/$projectKey/board'
      preLoaderRoute: typeof AppProjectsProjectKeyBoardRouteImport
      parentRoute: typeof AppProjectsProjectKeyRoute
    }
    '/_app/projects/$projectKey/backlog': {
      id: '/_app/projects/$projectKey/backlog'
      path: '/backlog'
      fullPath: '/projects/$projectKey/backlog'
      preLoaderRoute: typeof AppProjectsProjectKeyBacklogRouteImport
      parentRoute: typeof AppProjectsProjectKeyRoute
    }
  }
}

interface AppProjectsProjectKeyRouteChildren {
  AppProjectsProjectKeyBacklogRoute: typeof AppProjectsProjectKeyBacklogRoute
  AppProjectsProjectKeyBoardRoute: typeof AppProjectsProjectKeyBoardRoute
  AppProjectsProjectKeyMembersRoute: typeof AppProjectsProjectKeyMembersRoute
  AppProjectsProjectKeyRoadmapRoute: typeof AppProjectsProjectKeyRoadmapRoute
  AppProjectsProjectKeyIndexRoute: typeof AppProjectsProjectKeyIndexRoute
}

const AppProjectsProjectKeyRouteChildren: AppProjectsProjectKeyRouteChildren = {
  AppProjectsProjectKeyBacklogRoute: AppProjectsProjectKeyBacklogRoute,
  AppProjectsProjectKeyBoardRoute: AppProjectsProjectKeyBoardRoute,
  AppProjectsProjectKeyMembersRoute: AppProjectsProjectKeyMembersRoute,
  AppProjectsProjectKeyRoadmapRoute: AppProjectsProjectKeyRoadmapRoute,
  AppProjectsProjectKeyIndexRoute: AppProjectsProjectKeyIndexRoute,
}

const AppProjectsProjectKeyRouteWithChildren =
  AppProjectsProjectKeyRoute._addFileChildren(
    AppProjectsProjectKeyRouteChildren,
  )

interface AppProjectsRouteChildren {
  AppProjectsProjectKeyRoute: typeof AppProjectsProjectKeyRouteWithChildren
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsProjectKeyRoute: AppProjectsProjectKeyRouteWithChildren,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppRouteChildren {
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
  AppYourWorkRoute: typeof AppYourWorkRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProjectsRoute: AppProjectsRouteWithChildren,
  AppYourWorkRoute: AppYourWorkRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
